/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        brand: "#0261AA",
        white: "#FEFEFE",
        grey: "#484E50",
        black: "#2F3334",
        bgWhite: "#F9F9F9",
        bgDarker: "#F2F4F4",
        bgDark: "#EBEBEB",
        buttonLight: "#DFE3E4",
        iconsRounded: "#83BADF",
        icons: "#1F4569",
        graphic: "#DCDCDC",
      },
      fontFamily: {
        sans: ["Manrope", "sans-serif"],
      },
      fontSize: {
        h1: ["40px", { lineHeight: "55px", fontWeight: "400" }],
        h2: ["24px", { lineHeight: "29.3px", fontWeight: "400" }],
        h3: ["40px", { lineHeight: "55px", fontWeight: "400" }],
        h4bold: ["40px", { lineHeight: "45px", fontWeight: "700" }],
        h4citat: ["30px", { lineHeight: "36px", fontWeight: "200" }],
        h5: ["20px", { lineHeight: "28px", fontWeight: "700" }],
        h5timeline: ["18px", { lineHeight: "28px", fontWeight: "700" }],
        h6: ["20px", { lineHeight: "28px", fontWeight: "400" }],
        h7: ["18px", { lineHeight: "28px", fontWeight: "400" }],
        pStor: ["18px", { lineHeight: "20px", fontWeight: "400" }],
        p: ["18px", { lineHeight: "22.8px", fontWeight: "400" }],
        ps: ["14px", { lineHeight: "22.8px", fontWeight: "400" }],
        menu: ["18px", { lineHeight: "20px", fontWeight: "500" }],
        footer: ["22px", { lineHeight: "20px", fontWeight: "500" }],
        logo: ["28px", { lineHeight: "55px", fontWeight: "400" }],

        h1_mobile: ["28px", { lineHeight: "36px", fontWeight: "400" }],
        h2_mobile: ["16px", { lineHeight: "26px", fontWeight: "400" }],
        h3_mobile: ["28px", { lineHeight: "36px", fontWeight: "400" }],
        h4bold_mobile: ["28px", { lineHeight: "32px", fontWeight: "700" }],
        h4citat_mobile: ["22px", { lineHeight: "28px", fontWeight: "400" }],
        h5_mobile: ["16px", { lineHeight: "22px", fontWeight: "600" }],
        h5timeline_mobile: ["14px", { lineHeight: "20px", fontWeight: "700" }],
        h6_mobile: ["16px", { lineHeight: "22px", fontWeight: "400" }],
        h7_mobile: ["14px", { lineHeight: "20px", fontWeight: "400" }],
        pStor_mobile: ["14px", { lineHeight: "20px", fontWeight: "400" }],
        p_mobile: ["14px", { lineHeight: "18px", fontWeight: "400" }],
        ps_mobile: ["11px", { lineHeight: "18px", fontWeight: "400" }],
        menu_mobile: ["14px", { lineHeight: "18px", fontWeight: "500" }],
        footer: ["16px", { lineHeight: "20px", fontWeight: "500" }],
        logo_mobile: ["24px", { lineHeight: "36px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
